name: Update Trader Data

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch Trader Page
        run: curl https://encora.it/traders/vndyne > trader.html

      - name: Commit Update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add trader.html
          git commit -m "Update trader data" || echo "No changes"
          git push
